### PR TITLE
refactor: replace fast-glob with tinyglobby

### PR DESCRIPTION
**Pull request by SuperchupuDev**
[`fast-glob`](https://npmgraph.js.org/?q=fast-glob) - 17 subdependencies
[`tinyglobby`](https://npmgraph.js.org/?q=tinyglobby) - 2 subdependencies

https://github.com/es-tooling/module-replacements/blob/main/docs/modules/glob.md#tinyglobby

See unjs/mkdist#237

Like #418 but switches to an even smaller library

### CODE REVIEW

**Comment by pi0** [comment]
Thanks! I might replace glob support later lib but seems better alternative.

**Comment by Barbapapazes** [comment]
Hey,

Don't the package `fast-glob` in the `package.json` be removed? 🤔

**Comment by pi0** [comment]
Nice spot. removed for next rc (1a65aefcc035e4908113667d8f8859c3070091bd)

**Comment by SuperchupuDev** [comment]
@pi0 unfortunately `fast-glob` is still in the dependency tree until unjs/mkdist#237 gets merged

**Comment by pi0** [comment]
As mentioned, it is mainly to experiment on beta releases until we make a stable decision for replacement across unjs tools.

**Pull request merged**
