### PR TITLE
fix: correct `.d.cts` default export type

### LINKED ISSUE #457: The default export declaring in `.d.cts` is not accurate.
### Environment

Node.js: *
unbuild: v3.0.1

### Reproduction

https://stackblitz.com/edit/vitejs-vite-t55rnaxz?file=package.json,tsconfig.json,build.config.ts,src%2Findex.ts,dist%2Findex.d.cts&terminal=dev

### Describe the bug

First run `build`, this will emit the `cjs` output.

The source `index.ts` only contains a default export: 
```ts
export default function add(): number {
  return 42
}
```

In the `index.cjs` output, there is only the default export (this is correct ✅): 
```ts
module.exports = add;
```

But the `index.d.cts` output, it's:
```ts
export { add as default };
```
this is wrong ❌, because this would lead to [❗️ Incorrect default export](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FalseExportDefault.md) . You can run `check` to verify this problem.

And it should be:

```ts
export = add;
```

Another build tool [tsup](https://github.com/egoist/tsup) could have encountered the same problem, but they introduced a fix for this: 
https://github.com/egoist/tsup/blob/cd03e1e00ec2bd6676ae1837cbc7e618ab6a2362/src/rollup.ts#L92-L109

They manually replaced this from `export { XXX as default };` to `export = XXX;`

I'm wondering if we could do the same for unbuild ❤️.

(If that's the solution, I can popup a PR for it 🙌🏻)

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by kricsleo**
resolves #457

### CODE REVIEW

**Comment by kricsleo** [comment]
I've tested against the [./example/1.zero-config](https://github.com/unjs/unbuild/tree/main/examples/1.zero-config) and the output of `utils.d.cts` has changed from: 

```ts
declare function sum(a: number, b: number): number;

export { sum as default };
```

to: 

```ts
declare function sum(a: number, b: number): number;

export = sum;
```

This is the expected types in pair with the `utils.cjs` output:

```js
'use strict';

function sum(a, b) {
  return a + b;
}

module.exports = sum;
```

**Review by danielroe — APPROVED** [review]
this looks good to me!

an optimisation might be to use `findExports` from `mlly` rather than maintaining a separate regexp

**Comment by userquin** [comment]
Looks like we also need to include d.ts for node10 module resolution: I'm updating unbuild to 3.2.0 in UnoCSS repo and d.ts files are wrong.

**Comment by danielroe** [comment]
that would depend on whether it was type: module, i assume?

**Comment by userquin** [comment]
yes, we also have some problems with CJS and node16, for example, postcss package exporting default and a type, this PR doesn't change it:

```js
// d.cts
export { type UnoPostcssPluginOptions, unocss as default };
```
should be:
```js
export = unocss;
export { type UnoPostcssPluginOptions };
```

imagen

**Comment by userquin** [comment]
Even with type set to commonjs, unbuild generating wrong dts files, check https://github.com/unjs/unbuild/issues/474, reproduction there

**Pull request merged**
