### PR TITLE
(Draft) Rolldown support

### PR DESCRIPTION
**Pull request by OskarLebuda**
This PR is WIP example of implementation [rolldown](https://rolldown.rs/) as next bundler for the project.

Resolves https://github.com/unjs/unbuild/issues/451

Todo:
- [ ]  Support for `d.ts` (see https://github.com/rolldown/rolldown/issues/819)
- [ ] Support for TS-Decorators (see https://github.com/rolldown/rolldown/issues/2296)
- [ ] Watch mode
- [ ] Support for rollup plugins

### CODE REVIEW

**Comment by OskarLebuda** [comment]
@pi0 what do you think about this integration? Can I support it?

**Comment by pi0** [comment]
Thanks for PR ❤️ , early updating you that I plan to work on a new tool based on rolldown + OXC as there are significant changes (eg how we handle type declarations) 

I will invite you asap if you like to be involved 👍🏼

**Comment by OskarLebuda** [comment]
I'd be happy to help! I like projects like this so let me know if you need any help with that :)

**Comment by OskarLebuda** [comment]
@pi0 how about the `rspack` support for unbuild? Also working on that. Should I created PR? Or you think it's not worth? Of cours love to be invited to the new project ❤️

**Comment by OskarLebuda** [comment]
@pi0 cloasing this since the new project you mention.

**Comment by pi0** [comment]
https://www.npmjs.com/package/obuild (not public yet)

**Pull request closed without merging**
