### PR TITLE
refactor: use `jiti.import` for esm stubs and improve templates

### PR DESCRIPTION
**Pull request by antfu**
requires https://github.com/unjs/jiti/pull/158

### CODE REVIEW

**Comment by pi0** [comment]
@vargasmesh Yes! For non-mkdist and bundled entried that currently use `jiti` stub it will resolve possible issues. 

I would recommend btw to completely use mkdist build (non bundled) for your component library. It should fix it right away without waiting for this (as well as other benefits)

**Comment by vargasmesh** [comment]
@pi0 how can I make stub work for mkdist build? Here is my `build.config.ts`:

```ts
export default defineBuildConfig({
  entries: [
    {
      builder: "mkdist",
      input: "src/",
      outDir: "dist/",
    },
    {
      builder: "mkdist",
      input: "src/",
      outDir: "dist/",
      format: "cjs",
    },
  ],
  declaration: true,
  clean: true,
});
```
Vite raises:
```
[vite] Internal server error: Failed to resolve entry for package "vue-shining-text". The package may have incorrect main/module/exports specified in its package.json.
```

**Comment by pi0** [comment]
I think your issue is mainly about `package.json` field (which is unrelated to this one). If you can open an issue in your repo (if public) or a discussion would be happy to help 👍🏼

**Comment by vargasmesh** [comment]
Here is the https://github.com/vargasmesh/shining-text repository. Here is my config:
```json
"type": "module",
  "exports": {
    ".": {
      "import": "./dist/index.mjs",
      "require": "./dist/index.js"
    }
  },
  "main": "./dist/index.js",
  "types": "./dist/index.d.ts",
  "files": [
    "dist"
  ]
  ```
  The only thing I changed was replacing `/dist/index.cjs` for `/dist/index.js`
  
  I don't know why it does not create an `index.cjs`file

**Comment by pi0** [comment]
Let's continue on https://github.com/vargasmesh/shining-text/issues/1 👍🏼

**Comment by pi0** [comment]
Updated implementation to allow iterating. From what i extracted for now and need to do in next steps

- We need to resolve jiti's esm entry path for esm (and avoid windows path to url normalization for vite support?)
- We need to pass native `_import` implementation to `jiti.import`

**Pull request merged**
